version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      docker-semver-group:
        update-types:
        - "minor"
        - "patch"
